FROM node:20-alpine

WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.33.0 --activate
COPY . .
RUN pnpm install --frozen-lockfile \
  && pnpm store prune

ENV NODE_ENV=production
CMD ["pnpm", "--filter", "worker", "run", "start"]